spring:
  cloud:
    consul:
      host: localhost # Consul server address
      port: 8500      # Consul server port
      discovery:
        enabled: true  # Enable service discovery
        service-name: ProductService # Name of the service
server:
  port: 8088
